# System Configuration
system:
  # Define the type of system: HIGH, MEDIUM, LOW
  power_mode: "MEDIUM"  # Options: HIGH, MEDIUM, LOW
  # Define the system's available resources
  gpu_available: true
  total_ram_gb: 16  # GB of RAM available on the system
  cpu_cores: 8  # Number of physical CPU cores

# YOLO Model Configuration
yolo_model:
  # Model selection based on power_mode
  high_power_model: "yolov8m.pt"  # Medium model for high-power systems
  medium_power_model: "yolov8s.pt"  # Small model for medium-power systems
  low_power_model: "yolov8n.pt"  # Nano model for low-power systems

# Video Stream Configuration
video_stream:
  # Source of video (local webcam or RTSP stream URL)
  video_source: 0  # Change to RTSP URL if needed for drone feed
  fps_limit: 30  # FPS limit for video processing
  frame_skip: 1  # Frame skipping for dynamic power saving

# Detection Configuration
detection:
  # Minimum confidence threshold for object detection (person detection)
  confidence_threshold: 0.25
  bounding_box_color: [0, 255, 0]  # RGB color for bounding box
  label_font: "cv2.FONT_HERSHEY_SIMPLEX"
  label_font_scale: 0.5
  label_thickness: 2

# Dataset Configuration
dataset:
  # Directory to store the images of detected persons
  save_path: "Dataset"  # Folder where images will be saved
  image_format: ".jpg"  # Image format for saving
  max_images: 1000  # Maximum number of images to store

# Cloud Storage Configuration (Optional)
cloud_storage:
  enabled: false  # Set to true if using cloud storage
  provider: "AWS"  # Options: AWS, GCP, Azure
  bucket_name: "your-bucket-name"  # Cloud storage bucket name
  access_key: "your-access-key"  # Cloud storage access key
  secret_key: "your-secret-key"  # Cloud storage secret key
  region: "us-west-2"  # Cloud storage region (only applicable for AWS)

# Logging Configuration
logging:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  log_file: "logs/app.log"  # Path to the log file
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log format

# Resource Configuration
resource:
  # Path to store trained YOLO models locally
  model_storage_path: "/models"
  # RAM usage limit in MB
  ram_usage_limit: 8192  # 8 GB RAM
  # CPU usage limit (percent)
  cpu_usage_limit: 85  # 85% CPU usage limit
